"use client";

import { ArrowLeft, Copy, Download, FilePlus2, LockKeyhole, Mail, Send, Sparkles } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
type Draft={subject:string;heading:string;body:string;button:string};
function draftFor(type:string,prompt:string):Draft{const clean=prompt.trim()||"We have an important update for you.";const map:Record<string,{s:string;h:string;b:string}>={Welcome:{s:"Welcome to VPANSAK",h:"Welcome to a smarter shopping experience.",b:"Your VPANSAK account is ready. Explore products, save favorites and track every order from one secure dashboard."},"Order Update":{s:"An update about your VPANSAK order",h:"Your order status has changed.",b:clean},"Ticket Update":{s:"VPANSAK Support has an update",h:"There is a new update on your support request.",b:clean},Refund:{s:"Your VPANSAK refund update",h:"Refund status update",b:clean},Seller:{s:"VPANSAK Seller Center update",h:"An update about your seller account.",b:clean},Custom:{s:"A message from VPANSAK",h:"VPANSAK Update",b:clean}};const v=map[type]||map.Custom;return{subject:v.s,heading:v.h,body:v.b,button:type.includes("Ticket")?"Track Ticket":type.includes("Order")?"Track Order":"Open VPANSAK"}}
export default function EmailStudio(){const [denied,setDenied]=useState(false);const [ready,setReady]=useState(false);const [recipient,setRecipient]=useState("");const [draft,setDraft]=useState<Draft|null>(null);const [files,setFiles]=useState<string[]>([]);useEffect(()=>{const timer=window.setTimeout(async()=>{const res=await fetch("/api/admin");setDenied(res.status===403);setReady(true)},0);return()=>window.clearTimeout(timer)},[]);if(!ready)return <main className="account-loading"><span/><p>Opening Email Studio…</p></main>;if(denied)return <main className="admin-denied"><div><span><LockKeyhole/></span><h1>Admin access denied.</h1><Link href="/">Return to store</Link></div></main>;
 const generate=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setRecipient(String(f.get("recipient")||""));setDraft(draftFor(String(f.get("type")),String(f.get("prompt"))))};const html=draft?`<!doctype html><html><body style="margin:0;background:#f3f6fa;font-family:Arial"><div style="max-width:620px;margin:30px auto;background:white"><div style="padding:24px;background:#07162a;color:white"><b style="font-size:24px">VPANSAK</b><div style="font-size:10px;color:#86a4c7">POWERED BY A&A GROUP</div></div><div style="padding:36px"><h1 style="color:#10223a">${draft.heading}</h1><p style="color:#617188;line-height:1.7">${draft.body}</p><a href="https://vpansak.vercel.app" style="display:inline-block;padding:13px 20px;background:#1766ef;color:white;text-decoration:none;border-radius:6px">${draft.button}</a></div><div style="padding:20px;background:#f1f5fa;color:#7a899b;font-size:11px">support.vpansak@gmail.com • VPANSAK</div></div></body></html>`:"";
 return <main className="email-studio"><header className="sub-header"><Link className="shop-brand" href="/"><img className="brand-logo" src="/vpansak-logo-dark.jpeg" alt="VPANSAK"/><span><strong>VPANSAK</strong><small>EMAIL STUDIO</small></span></Link><nav><Link href="/admin/manage"><ArrowLeft/>Admin Console</Link></nav></header><section className="email-studio-hero"><Sparkles/><small>SMART EMAIL CREATOR</small><h1>Professional VPANSAK emails.</h1><p>Generate a branded subject, message, action button and responsive HTML preview.</p></section><section className="email-studio-layout"><form onSubmit={generate}><label>Recipient email<input name="recipient" type="email" required placeholder="customer@example.com"/></label><label>Email type<select name="type"><option>Welcome</option><option>Order Update</option><option>Ticket Update</option><option>Refund</option><option>Seller</option><option>Custom</option></select></label><label>Writing prompt<textarea name="prompt" required placeholder="Explain what happened and the action the recipient should take…"/></label><label className="attachment"><FilePlus2/>Add attachments<input type="file" multiple onChange={(e)=>setFiles(Array.from(e.target.files||[]).map((f)=>f.name))}/><small>{files.length?files.join(", "):"Attachments remain on your device until you send from your email app."}</small></label><button><Sparkles/>Generate email draft</button><p>Automated Gmail sending activates after production Gmail credentials are connected.</p></form><div className="email-preview">{draft?<><div className="email-actions"><button onClick={()=>navigator.clipboard?.writeText(`${draft.subject}\n\n${draft.body}`)}><Copy/>Copy</button><button onClick={()=>{const blob=new Blob([html],{type:"text/html"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="vpansak-email.html";a.click();URL.revokeObjectURL(url)}}><Download/>Download HTML</button><a href={`mailto:${encodeURIComponent(recipient)}?subject=${encodeURIComponent(draft.subject)}&body=${encodeURIComponent(draft.body)}`}><Send/>Open email app</a></div><article><header><strong>VPANSAK</strong><small>POWERED BY A&amp;A GROUP</small></header><div><small>SUBJECT: {draft.subject}</small><h2>{draft.heading}</h2><p>{draft.body}</p><span>{draft.button}</span></div><footer><Mail/>support.vpansak@gmail.com • VPANSAK</footer></article></>:<div className="email-empty"><Mail/><h3>Email preview</h3><p>Your generated branded email will appear here.</p></div>}</div></section></main>}
