"use client";

import { Award, Banknote, CheckCircle2, Copy, CreditCard, ExternalLink, HeartHandshake, Printer, QrCode, Search, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
type Certificate={certificateId:string;donorName:string;amount:number;appreciationMessage:string;createdAt:string;paymentStatus:string};
declare global{interface Window{Razorpay?:new(options:Record<string,unknown>)=>{open:()=>void;on:(event:string,callback:(data:{error?:{description?:string}})=>void)=>void}}}
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
async function loadRazorpay(){if(window.Razorpay)return true;return new Promise<boolean>((resolve)=>{const s=document.createElement("script");s.src="https://checkout.razorpay.com/v1/checkout.js";s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
export default function FoundationPage(){
 const query=useSearchParams();
 const [certificate,setCertificate]=useState<Certificate|null>(null);const [lookup,setLookup]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [method,setMethod]=useState("razorpay");const [copied,setCopied]=useState("");
 useEffect(()=>{const id=query.get("certificate")?.trim().toUpperCase();if(!id||!/^VPC\d{6}$/.test(id))return;setLookup(id);fetch(`/api/donations?certificate=${encodeURIComponent(id)}`).then(async(res)=>({res,data:await res.json()})).then(({res,data})=>{if(res.ok)setCertificate(data.certificate);else setError(data.error||"Certificate not found")}).catch(()=>setError("Certificate lookup unavailable"))},[query]);
 const copy=async(value:string,label:string)=>{await navigator.clipboard?.writeText(value);setCopied(`${label} copied`);setTimeout(()=>setCopied(""),1800)};
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const element=e.currentTarget;const f=new FormData(element);const details={name:f.get("name"),email:f.get("email"),mobile:f.get("mobile"),amount:Number(f.get("amount"))};setBusy(true);setError("");try{
  if(method==="razorpay"){if(!(await loadRazorpay()))throw new Error("Razorpay load nahi hua. Internet check karein.");const start=await fetch("/api/donations/payment/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(details)});const setup=await start.json();if(!start.ok)throw new Error(setup.error||"Payment start nahi hua");await new Promise<void>((resolve,reject)=>{const r=new window.Razorpay!({key:setup.keyId,amount:setup.order.amount,currency:"INR",name:"VPANSAK Support Fund",description:"Voluntary support contribution",image:"/vpansak-logo-light.jpeg",order_id:setup.order.id,prefill:{name:details.name,email:details.email,contact:details.mobile},theme:{color:"#1766ef"},modal:{ondismiss:()=>reject(new Error("Payment cancel kar diya gaya."))},handler:async(response:Record<string,string>)=>{const verify=await fetch("/api/donations/payment/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...details,...response,donationId:setup.donationId,certificateId:setup.certificateId})});const data=await verify.json();if(!verify.ok){reject(new Error(data.error||"Payment verification failed"));return}setCertificate({...data,createdAt:new Date().toISOString()});setLookup(data.certificateId);element.reset();resolve()}});r.on("payment.failed",(response)=>reject(new Error(response.error?.description||"Payment failed")));r.open()})
  }else{const transaction=String(f.get("transactionId")||"").trim();if(!transaction)throw new Error("Payment ke baad Transaction/UTR ID enter karein.");const paymentMethod=method==="bank"?`Bank transfer • ${transaction}`:`UPI • ${transaction}`;const res=await fetch("/api/donations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...details,paymentMethod})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Record create nahi hua");setCertificate({...data,createdAt:new Date().toISOString()});setLookup(data.certificateId);element.reset()}
 }catch(err){setError(err instanceof Error?err.message:"Contribution could not be completed")}finally{setBusy(false)}};
 const verify=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");const res=await fetch(`/api/donations?certificate=${encodeURIComponent(lookup.trim().toUpperCase())}`);const data=await res.json();if(res.ok)setCertificate(data.certificate);else{setCertificate(null);setError(data.error||"Certificate not found")}setBusy(false)};
 return <main className="foundation-page"><header className="sub-header"><Link className="shop-brand" href="/"><img className="brand-logo" src="/vpansak-logo-dark.jpeg" alt="VPANSAK"/><span><strong>VPANSAK</strong><small>SUPPORT FUND</small></span></Link><nav><Link href="/">Main store</Link><Link href="/support">Support Hub</Link><a href="mailto:support.vpansak@gmail.com">Contact</a></nav></header>
 <section className="foundation-hero"><div><small>VPANSAK SUPPORT FUND</small><h1>Support that creates opportunity.</h1><p>Choose a secure contribution method, receive a verifiable Certificate ID and print an appreciation certificate after verification.</p><span><ShieldCheck/>Voluntary support • No 80G tax-exemption claim</span></div><div className="foundation-mark"><HeartHandshake/><b>A&amp;A</b><small>COMMUNITY INITIATIVE</small></div></section>
 <section className="support-payment-grid"><button className={method==="razorpay"?"active":""} onClick={()=>setMethod("razorpay")}><CreditCard/><span><strong>Razorpay API</strong><small>UPI, cards, netbanking &amp; wallets</small></span></button><a href="https://rzp.io/rzp/suppovpansak" target="_blank" rel="noreferrer"><ExternalLink/><span><strong>Razorpay Payment Page</strong><small>Open secure hosted payment link</small></span></a><button className={method==="bank"?"active":""} onClick={()=>setMethod("bank")}><Banknote/><span><strong>Bank Transfer</strong><small>NEFT / IMPS / bank transfer</small></span></button><button className={method==="upi"?"active":""} onClick={()=>setMethod("upi")}><QrCode/><span><strong>QR / UPI</strong><small>Scan QR or copy UPI ID</small></span></button></section>
 <section className="support-payment-details">{method==="bank"&&<article><h3>Bank transfer details</h3><dl><div><dt>Account number</dt><dd>6057110365 <button onClick={()=>copy("6057110365","Account number")}><Copy/></button></dd></div><div><dt>IFSC code</dt><dd>KKBK0005359 <button onClick={()=>copy("KKBK0005359","IFSC")}><Copy/></button></dd></div><div><dt>Home branch</dt><dd>GORAKHPUR – TARAMANDAL</dd></div><div><dt>Bank UPI ID</dt><dd>8738869635@kotakbank <button onClick={()=>copy("8738869635@kotakbank","UPI ID")}><Copy/></button></dd></div></dl></article>}{method==="upi"&&<article className="support-qr"><img src="/vpansak-support-qr.jpeg" alt="VPANSAK support UPI QR code"/><div><h3>Scan and pay</h3><p>Any UPI app se QR scan karein, ya UPI ID copy karein.</p><button onClick={()=>copy("alookk@ptyes","UPI ID")}><Copy/>alookk@ptyes</button></div></article>}{copied&&<span className="support-copy-toast">{copied}</span>}</section>
 <section className="foundation-shell"><div className="donation-form"><small>SUPPORT CONTRIBUTION</small><h2>{method==="razorpay"?"Pay securely with Razorpay":"Submit payment reference"}</h2><p>Razorpay API payments are verified automatically. Bank/QR payments remain <b>Pending Verification</b> until checked.</p>{error&&<button className="support-alert" onClick={()=>setError("")}>{error}</button>}<form onSubmit={create}><label>Full name<input name="name" required maxLength={100}/></label><label>Email address<input name="email" type="email" required maxLength={150}/></label><label>Mobile number<input name="mobile" required inputMode="numeric" pattern="[6-9][0-9]{9}" maxLength={10}/></label><label>Contribution amount (₹)<input name="amount" type="number" min="1" max="1000000" step="1" required/></label>{method!=="razorpay"&&<label>Transaction / UTR ID<input name="transactionId" required maxLength={80} placeholder="Enter after completing payment"/></label>}<button disabled={busy}>{busy?"Please wait…":method==="razorpay"?"Pay securely":"Submit for verification"}<Award/></button></form><div className="donation-safety"><ShieldCheck/><p><strong>Payment safety</strong><br/>Never share OTP, UPI PIN, card PIN, CVV or banking password. Contributions are not currently advertised as eligible for 80G tax deduction.</p></div></div>
 <div className="certificate-area"><div className="certificate-toolbar"><form onSubmit={verify}><Search/><input value={lookup} onChange={(e)=>setLookup(e.target.value.toUpperCase())} placeholder="Verify VPC123456" maxLength={9}/><button disabled={busy}>Verify</button></form>{certificate&&<button onClick={()=>window.print()}><Printer/>Print / Save PDF</button>}</div>{certificate?<article className="donation-certificate"><div className="certificate-border"><header><img src="/vpansak-logo-light.jpeg" alt="VPANSAK logo"/><div><strong>VPANSAK</strong><span>SUPPORT FUND</span></div></header><Sparkles/><small>CERTIFICATE OF APPRECIATION</small><h2>Presented with gratitude to</h2><h1>{certificate.donorName}</h1><p>{certificate.appreciationMessage}</p><div className="certificate-amount"><span>CONTRIBUTION RECORDED</span><strong>{money(certificate.amount)}</strong><small>Issued on {new Date(certificate.createdAt).toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"})}</small></div><footer><div className="founder-sign"><img src="/founder-signature.png" alt="Alok Singh signature"/><b>Alok Singh</b><span>Founder &amp; Authorized Signatory</span></div><div><b>{certificate.certificateId}</b><span>Permanent Verifiable Certificate ID</span></div></footer><div className="certificate-status"><CheckCircle2/>{certificate.paymentStatus}</div></div></article>:<div className="certificate-placeholder"><Award/><h3>Your certificate preview</h3><p>Complete a contribution or verify an existing Certificate ID.</p></div>}</div></section>
 <section className="foundation-values"><article><span>01</span><h3>Automatic verification</h3><p>Razorpay API payment is verified before a confirmed record is issued.</p></article><article><span>02</span><h3>Manual alternatives</h3><p>Bank and QR contributions can be submitted with a transaction reference.</p></article><article><span>03</span><h3>Clear status</h3><p>Every certificate shows whether the contribution has been verified.</p></article></section></main>
}
