"use client";

import { ArrowLeft, Baby, Bike, BookOpen, Boxes, Dumbbell, Gamepad2, HeartPulse, Home, Laptop, Search, Shirt, ShoppingBag, Smartphone, Sparkles, UtensilsCrossed, Watch, WashingMachine } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { catalogProducts } from "../lib/catalog";
const categories=[{n:"Fashion",I:Shirt},{n:"Electronics",I:Laptop},{n:"Mobile",I:Smartphone},{n:"Beauty",I:Sparkles},{n:"Grocery",I:ShoppingBag},{n:"Books",I:BookOpen},{n:"Home",I:Home},{n:"Appliances",I:WashingMachine},{n:"Sports",I:Dumbbell},{n:"Toys",I:Baby},{n:"Accessories",I:Watch},{n:"Lifestyle",I:HeartPulse},{n:"Computer",I:Laptop},{n:"Gaming",I:Gamepad2},{n:"Kitchen",I:UtensilsCrossed},{n:"Furniture",I:Boxes},{n:"Healthcare",I:HeartPulse},{n:"Automotive",I:Bike}];
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
export default function CategoriesPage(){const [search,setSearch]=useState("");const [selected,setSelected]=useState("All");const results=useMemo(()=>catalogProducts.filter((p)=>(selected==="All"||p.category===selected)&&(p.name.toLowerCase().includes(search.toLowerCase())||p.category.toLowerCase().includes(search.toLowerCase()))),[search,selected]);return <main className="categories-page"><header className="sub-header"><Link className="shop-brand" href="/"><img className="brand-logo" src="/vpansak-logo-dark.jpeg" alt="VPANSAK"/><span><strong>VPANSAK</strong><small>ALL CATEGORIES</small></span></Link><nav><Link href="/"><ArrowLeft/>Store</Link><Link href="/account">My account</Link></nav></header><section className="categories-hero"><small>EXPLORE EVERY DEPARTMENT</small><h1>What are you looking for?</h1><label><Search/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search categories or products…"/></label></section><section className="all-category-grid"><button className={selected==="All"?"active":""} onClick={()=>setSelected("All")}><Boxes/><strong>All products</strong><small>Browse everything</small></button>{categories.map(({n,I})=><button className={selected===n?"active":""} onClick={()=>setSelected(n)} key={n}><I/><strong>{n}</strong><small>Explore department</small></button>)}</section><section className="category-results"><header><div><small>PRODUCT DISCOVERY</small><h2>{selected} {selected==="All"?"catalog":"collection"}</h2></div><span>{results.length} products available</span></header><div>{results.length?results.map((p)=><Link href={`/product/${p.id}`} key={p.id}><img src={p.imageUrl} alt={p.name}/><span><small>{p.category}</small><strong>{p.name}</strong><b>{money(p.price)}</b></span></Link>):<div className="category-empty"><Search/><h3>No live products in this category yet</h3><p>VPANSAK official in-house products for this category are launching soon.</p></div>}</div></section></main>}
