"use client";

import { Bell, ChevronRight, Heart, Home, LogIn, MapPin, PackageCheck, Plus, Save, ShieldCheck, ShoppingCart, Trash2, UserRound } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { catalogProducts } from "../lib/catalog";

type AccountData={email:string;profile:{fullName:string;mobile:string}|null;addresses:Array<{id:number;label:string;fullName:string;mobile:string;line1:string;city:string;state:string;pinCode:string;isPrimary:boolean}>;wishlist:Array<{id:number;productId:string}>;cart:Array<{id:number;productId:string;quantity:number}>;orders:Array<{orderId:string;total:number;status:string;createdAt:string;paymentMethod:string}>;notifications:Array<{id:number;title:string;message:string;read:boolean;createdAt:string}>};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const accountTabs=[{key:"overview",Icon:Home,label:"Overview"},{key:"orders",Icon:PackageCheck,label:"My orders"},{key:"addresses",Icon:MapPin,label:"Address book"},{key:"wishlist",Icon:Heart,label:"Wishlist"},{key:"cart",Icon:ShoppingCart,label:"Saved cart"},{key:"notifications",Icon:Bell,label:"Notifications"},{key:"profile",Icon:UserRound,label:"Profile settings"}];

export default function AccountPage(){
  const [data,setData]=useState<AccountData|null>(null);const [loading,setLoading]=useState(true);const [unauthorized,setUnauthorized]=useState(false);const [tab,setTab]=useState("overview");const [message,setMessage]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const res=await fetch("/api/account");if(res.status===401){setUnauthorized(true);setLoading(false);return;}const value=await res.json();if(res.ok)setData(value);else setMessage(value.error||"Could not load account");}catch{setMessage("Could not load account");}setLoading(false);},[]);
  useEffect(()=>{void Promise.resolve().then(()=>load())},[load]);
  const wishProducts=useMemo(()=>data?.wishlist.map((item)=>catalogProducts.find((p)=>p.id===item.productId)).filter(Boolean)||[],[data]);
  const cartProducts=useMemo(()=>data?.cart.map((item)=>({item,product:catalogProducts.find((p)=>p.id===item.productId)})).filter((row)=>row.product)||[],[data]);
  const action=async(body:Record<string,unknown>)=>{const res=await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const value=await res.json();setMessage(res.ok?"Saved successfully":value.error||"Could not save");if(res.ok)await load();};
  if(loading)return <main className="account-loading"><span/><p>Loading your VPANSAK account…</p></main>;
  if(unauthorized)return <main className="account-signin"><div><img src="/vpansak-logo-light.jpeg" alt="VPANSAK"/><small>SECURE CUSTOMER ACCOUNT</small><h1>Sign in to continue.</h1><p>Your orders, addresses, wishlist, cart and notifications stay connected to your verified account.</p><a href="/signin-with-chatgpt?return_to=%2Faccount"><LogIn/>Sign in securely</a><Link href="/">Continue browsing</Link><span><ShieldCheck/>Protected account access</span></div></main>;
  return <main className="account-page">
    {message&&<button className="account-toast" onClick={()=>setMessage("")}>{message}</button>}
    <header className="sub-header"><Link className="shop-brand" href="/"><img className="brand-logo" src="/vpansak-logo-dark.jpeg" alt="VPANSAK"/><span><strong>VPANSAK</strong><small>MY ACCOUNT</small></span></Link><nav><Link href="/">Store</Link><Link href="/track">Track order</Link><a href="/signout-with-chatgpt?return_to=%2F">Sign out</a></nav></header>
    <div className="account-shell">
      <aside className="account-sidebar"><div className="account-user"><span><UserRound/></span><div><small>WELCOME</small><strong>{data?.profile?.fullName||data?.email.split("@")[0]}</strong><p>{data?.email}</p></div></div><nav>{accountTabs.map(({key,Icon,label})=><button className={tab===key?"active":""} key={key} onClick={()=>setTab(key)}><Icon/>{label}<ChevronRight/></button>)}</nav></aside>
      <section className="account-main">
        {tab==="overview"&&<><div className="account-title"><small>ACCOUNT OVERVIEW</small><h1>Your VPANSAK dashboard</h1><p>Manage everything related to your shopping account in one place.</p></div><div className="account-stats"><button onClick={()=>setTab("orders")}><PackageCheck/><span><strong>{data?.orders.length||0}</strong><small>Orders</small></span></button><button onClick={()=>setTab("addresses")}><MapPin/><span><strong>{data?.addresses.length||0}</strong><small>Addresses</small></span></button><button onClick={()=>setTab("wishlist")}><Heart/><span><strong>{data?.wishlist.length||0}</strong><small>Wishlist items</small></span></button><button onClick={()=>setTab("notifications")}><Bell/><span><strong>{data?.notifications.filter((n)=>!n.read).length||0}</strong><small>Unread updates</small></span></button></div><section className="account-card"><header><h2>Recent orders</h2><button onClick={()=>setTab("orders")}>View all</button></header>{data?.orders.length?data.orders.slice(0,4).map((order)=><div className="account-order" key={order.orderId}><span><strong>{order.orderId}</strong><small>{new Date(order.createdAt).toLocaleDateString("en-IN")}</small></span><span>{order.status}</span><b>{money(order.total)}</b><Link href={`/track?id=${order.orderId}`}>Track</Link></div>):<div className="account-empty"><PackageCheck/><h3>No orders yet</h3><Link href="/">Start shopping</Link></div>}</section></>}
        {tab==="orders"&&<><div className="account-title"><small>PURCHASE HISTORY</small><h1>My orders</h1></div><section className="account-card order-list">{data?.orders.length?data.orders.map((order)=><article key={order.orderId}><div><PackageCheck/><span><strong>{order.orderId}</strong><small>Placed {new Date(order.createdAt).toLocaleDateString("en-IN")}</small></span></div><span className="order-status">{order.status}</span><span><small>PAYMENT</small><strong>{order.paymentMethod}</strong></span><b>{money(order.total)}</b><Link href={`/track?id=${order.orderId}`}>View &amp; track <ChevronRight/></Link></article>):<div className="account-empty"><PackageCheck/><h3>No orders found</h3><Link href="/">Explore products</Link></div>}</section></>}
        {tab==="addresses"&&<><div className="account-title"><small>DELIVERY DETAILS</small><h1>Address book</h1></div><div className="address-grid">{data?.addresses.map((address)=><article key={address.id}>{address.isPrimary&&<span>PRIMARY</span>}<h3>{address.label}</h3><p><strong>{address.fullName}</strong><br/>{address.line1}<br/>{address.city}, {address.state} — {address.pinCode}<br/>{address.mobile}</p><button onClick={()=>action({action:"deleteAddress",id:address.id})}><Trash2/>Remove</button></article>)}<form onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);action({action:"address",label:f.get("label"),fullName:f.get("fullName"),mobile:f.get("mobile"),line1:f.get("line1"),city:f.get("city"),state:f.get("state"),pinCode:f.get("pinCode"),isPrimary:f.get("isPrimary")==="on"});e.currentTarget.reset()}}><h3><Plus/>Add new address</h3><div><input name="label" placeholder="Label (Home/Office)" required/><input name="fullName" placeholder="Full name" required/><input name="mobile" placeholder="Mobile" required/><input name="line1" placeholder="House, area and street" required/><input name="city" placeholder="City" required/><input name="state" placeholder="State" required/><input name="pinCode" placeholder="PIN code" required/><label><input type="checkbox" name="isPrimary"/>Set as primary</label></div><button><Save/>Save address</button></form></div></>}
        {tab==="wishlist"&&<><div className="account-title"><small>SAVED FOR LATER</small><h1>My wishlist</h1></div><div className="account-product-grid">{wishProducts.length?wishProducts.map((product)=>product&&<article key={product.id}><img src={product.imageUrl} alt={product.name}/><div><small>{product.category}</small><h3>{product.name}</h3><strong>{money(product.price)}</strong><Link href={`/product/${product.id}`}>View product</Link></div><button onClick={()=>action({action:"wishlist",productId:product.id})}><Trash2/></button></article>):<div className="account-empty"><Heart/><h3>Your wishlist is empty</h3><Link href="/">Discover products</Link></div>}</div></>}
        {tab==="cart"&&<><div className="account-title"><small>MULTI-DEVICE CART</small><h1>Saved cart</h1></div><div className="account-product-grid">{cartProducts.length?cartProducts.map(({item,product})=>product&&<article key={product.id}><img src={product.imageUrl} alt={product.name}/><div><small>Quantity: {item.quantity}</small><h3>{product.name}</h3><strong>{money(product.price*item.quantity)}</strong><Link href={`/product/${product.id}`}>View product</Link></div><button onClick={()=>action({action:"cart",productId:product.id,quantity:0})}><Trash2/></button></article>):<div className="account-empty"><ShoppingCart/><h3>Your saved cart is empty</h3><Link href="/">Continue shopping</Link></div>}</div></>}
        {tab==="notifications"&&<><div className="account-title"><small>ACCOUNT UPDATES</small><h1>Notifications</h1></div><section className="notification-list">{data?.notifications.length?data.notifications.map((item)=><button className={item.read?"read":""} key={item.id} onClick={()=>action({action:"readNotification",id:item.id})}><Bell/><span><strong>{item.title}</strong><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString("en-IN")}</small></span>{!item.read&&<i/>}</button>):<div className="account-empty"><Bell/><h3>No notifications yet</h3></div>}</section></>}
        {tab==="profile"&&<><div className="account-title"><small>PERSONAL INFORMATION</small><h1>Profile settings</h1></div><form className="profile-form" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);action({action:"profile",fullName:f.get("fullName"),mobile:f.get("mobile")})}}><label>Email address<input value={data?.email||""} disabled/></label><label>Full name<input name="fullName" defaultValue={data?.profile?.fullName||""} required/></label><label>Mobile number<input name="mobile" defaultValue={data?.profile?.mobile||""} required/></label><button><Save/>Save profile</button><p><ShieldCheck/>Your account identity is handled through secure sign-in.</p></form></>}
      </section>
    </div>
  </main>
}
