-- Supabase Schema Initialization SQL Script for VPANSAK Shopping
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/lffcguvwibkpwzzihpcp/sql)

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL DEFAULT 'NO_HASH',
  full_name TEXT NOT NULL,
  mobile TEXT DEFAULT '',
  role TEXT DEFAULT 'customer',
  profile_image TEXT,
  auth_provider TEXT DEFAULT 'email',
  google_user_id TEXT UNIQUE,
  email_verified INTEGER DEFAULT 1,
  account_status TEXT DEFAULT 'active',
  security_question_id TEXT,
  security_answer_hash TEXT,
  last_login_at TIMESTAMPTZ,
  password_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  email TEXT PRIMARY KEY,
  full_name TEXT NOT NULL DEFAULT '',
  mobile TEXT NOT NULL DEFAULT '',
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 3. Addresses Table
CREATE TABLE IF NOT EXISTS public.addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_email TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT 'Home',
  full_name TEXT NOT NULL,
  mobile TEXT NOT NULL,
  line1 TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  pin_code TEXT NOT NULL,
  is_primary BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 4. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL UNIQUE,
  owner_email TEXT,
  customer_name TEXT NOT NULL,
  mobile TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  pin_code TEXT NOT NULL,
  payment_method TEXT NOT NULL,
  total NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'Order Confirmed',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 5. Tickets Table
CREATE TABLE IF NOT EXISTS public.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id TEXT NOT NULL UNIQUE,
  customer_name TEXT NOT NULL,
  email TEXT NOT NULL,
  mobile TEXT DEFAULT '',
  category TEXT NOT NULL,
  subject TEXT NOT NULL,
  description TEXT DEFAULT '',
  priority TEXT DEFAULT 'Normal',
  status TEXT DEFAULT 'Open',
  assigned_officer TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 6. Cart Items Table
CREATE TABLE IF NOT EXISTS public.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_email TEXT NOT NULL,
  product_id TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cart_owner_product_unique UNIQUE (owner_email, product_id)
);

-- 7. Wishlist Items Table
CREATE TABLE IF NOT EXISTS public.wishlist_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_email TEXT NOT NULL,
  product_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT wishlist_owner_product_unique UNIQUE (owner_email, product_id)
);

-- 8. Donations Table
CREATE TABLE IF NOT EXISTS public.donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donation_id TEXT UNIQUE,
  certificate_id TEXT UNIQUE,
  donor_name TEXT NOT NULL,
  email TEXT,
  mobile TEXT,
  amount NUMERIC NOT NULL,
  appreciation_message TEXT,
  payment_status TEXT DEFAULT 'Pending Verification',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Disable RLS if present so service role & API client can write cleanly
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations DISABLE ROW LEVEL SECURITY;
