"use client";

import { ArrowLeft, BadgeCheck, Check, ChevronRight, Heart, Minus, PackageCheck, Plus, RotateCcw, Share2, ShieldCheck, ShoppingCart, Star, Truck } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { catalogProducts } from "../../lib/catalog";

const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);

export default function ProductPage(){
  const {id}=useParams<{id:string}>();
  const product=catalogProducts.find((item)=>item.id===id)??catalogProducts[0];
  const related=useMemo(()=>catalogProducts.filter((item)=>item.category===product.category&&item.id!==product.id).slice(0,4),[product]);
  const [image,setImage]=useState(product.imageUrl); const [qty,setQty]=useState(1); const [wish,setWish]=useState(false); const [toast,setToast]=useState("");
  const [reviews,setReviews]=useState<Array<{id:number;displayName:string;rating:number;title:string;body:string;createdAt:string}>>([]);
  useEffect(()=>{fetch(`/api/reviews?product=${encodeURIComponent(product.id)}`).then(r=>r.json()).then(d=>setReviews(d.reviews||[])).catch(()=>{});},[product.id]);
  const notice=(text:string)=>{setToast(text);setTimeout(()=>setToast(""),2200)};
  const add=async()=>{try{const response=await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"cart",productId:product.id,quantity:qty})});if(response.ok)notice("Saved to your account cart");else if(response.status===401)notice("Sign in to save this cart across devices");else notice("Cart could not be saved");}catch{notice("Cart could not be saved")}};
  const toggleWish=async()=>{setWish(!wish);try{const response=await fetch("/api/account",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"wishlist",productId:product.id})});if(response.status===401)notice("Sign in to sync your wishlist");else notice(wish?"Removed from wishlist":"Saved to wishlist")}catch{notice("Wishlist updated on this page")}};
  const submitReview=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const response=await fetch("/api/reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId:product.id,displayName:form.get("name"),rating:Number(form.get("rating")),title:form.get("title"),body:form.get("body")})});const data=await response.json();notice(response.ok?"Review submitted for approval":data.error||"Could not submit review");if(response.ok)formElement.reset();};
  return <main className="product-page">
    {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
    <header className="sub-header"><Link className="shop-brand" href="/"><img className="brand-logo" src="/vpansak-logo-dark.jpeg" alt="VPANSAK"/><span><strong>VPANSAK</strong><small>SHOPPING</small></span></Link><nav><Link href="/"><ArrowLeft/>Back to store</Link><Link href="/account">My account</Link><Link href="/support">Support</Link></nav></header>
    <div className="breadcrumb"><Link href="/">Home</Link><ChevronRight/><span>{product.category}</span><ChevronRight/><strong>{product.name}</strong></div>
    <section className="product-detail">
      <div className="product-gallery"><div className="thumbs">{product.images.map((src)=><button className={src===image?"active":""} key={src} onClick={()=>setImage(src)}><img src={src} alt=""/></button>)}</div><div className="main-product-image"><img src={image} alt={product.name}/><span>Hover-ready high resolution image</span></div></div>
      <div className="product-summary"><small>{product.brand} • {product.category}</small><h1>{product.name}</h1><div className="detail-rating"><strong>{(product.rating/10).toFixed(1)} <Star fill="currentColor"/></strong><span>{product.reviewCount.toLocaleString("en-IN")} verified ratings</span></div><p className="product-description">{product.description}</p><div className="detail-price"><strong>{money(product.price)}</strong><s>{money(product.mrp)}</s><span>{Math.round((1-product.price/product.mrp)*100)}% off</span></div><p className="tax-note">Inclusive of all taxes</p>
        <div className="offer-box"><b>Available offers</b><p><BadgeCheck/>Welcome offer: Use VPANSAK10 for up to ₹300 off</p><p><BadgeCheck/>Free delivery on this product</p><p><BadgeCheck/>Secure payment options available</p></div>
        <div className="delivery-box"><Truck/><div><strong>Delivery check</strong><label><input placeholder="Enter PIN code" inputMode="numeric"/><button onClick={()=>notice("Delivery available for eligible PIN codes")}>Check</button></label><small>Estimated dispatch within 1–3 business days</small></div></div>
        <div className="purchase-row"><div className="detail-qty"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><b>{qty}</b><button onClick={()=>setQty(Math.min(10,qty+1))}><Plus/></button></div><button className="add-detail" onClick={add}><ShoppingCart/>Add to cart</button><button className="buy-detail" onClick={()=>{window.location.href=`/checkout?product=${product.id}&qty=${qty}`}}>Buy now</button><button className={wish?"wish-detail active":"wish-detail"} onClick={toggleWish}><Heart fill={wish?"currentColor":"none"}/></button><button className="share-detail" onClick={()=>{navigator.clipboard?.writeText(location.href);notice("Product link copied")}}><Share2/></button></div>
        <div className="product-assurances"><span><ShieldCheck/><b>Secure payment</b></span><span><RotateCcw/><b>Easy support</b></span><span><PackageCheck/><b>Verified listing</b></span></div>
      </div>
    </section>
    <section className="product-content"><article><h2>Product description</h2><p>{product.description} Every listing includes transparent pricing, stock visibility and VPANSAK support access.</p></article><article><h2>Specifications</h2><dl>{Object.entries(product.specifications).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></article></section>
    <section className="review-section"><div className="review-head"><div><small>CUSTOMER REVIEWS</small><h2>Reviews &amp; ratings</h2></div><div className="score"><strong>{(product.rating/10).toFixed(1)}</strong><span>★</span><small>{product.reviewCount} ratings</small></div></div><div className="review-layout"><div className="review-list">{reviews.length?reviews.map((review)=><article key={review.id}><div><strong>{review.displayName}</strong><span>{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</span></div><h3>{review.title}</h3><p>{review.body}</p><small>{new Date(review.createdAt).toLocaleDateString("en-IN")}</small></article>):<div className="no-reviews"><Star/><h3>No approved written reviews yet</h3><p>Be the first verified customer to share useful feedback.</p></div>}</div><form className="review-form" onSubmit={submitReview}><h3>Write a review</h3><label>Display name<input name="name" required/></label><label>Rating<select name="rating" defaultValue="5"><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Average</option><option value="2">2 — Poor</option><option value="1">1 — Very poor</option></select></label><label>Review title<input name="title" required/></label><label>Your review<textarea name="body" required minLength={10}/></label><button>Submit for approval</button><small>Sign-in is required. Reviews appear after admin approval.</small></form></div></section>
    <section className="related-section"><small>YOU MAY ALSO LIKE</small><h2>Similar products</h2><div>{related.map((item)=><Link href={`/product/${item.id}`} key={item.id}><img src={item.imageUrl} alt={item.name}/><span><small>{item.category}</small><strong>{item.name}</strong><b>{money(item.price)}</b></span></Link>)}</div></section>
  </main>;
}
