"use client";

import { ArrowLeft, CheckCircle2, FileText, Mail, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";

const policies:Record<string,{title:string;intro:string;sections:Array<{h:string;p:string}>}>={
 "privacy-policy":{title:"Privacy Policy",intro:"How VPANSAK collects, uses and protects information across shopping, support and seller services.",sections:[{h:"Information we collect",p:"We collect details you provide for accounts, orders, delivery addresses, support tickets, reviews, seller applications and donation certificates. Technical information may be used to keep the platform secure and reliable."},{h:"How information is used",p:"Information is used to operate orders, provide customer support, review seller KYC, prevent misuse, improve services and send essential account updates. We do not ask for OTPs, UPI PINs or card PINs."},{h:"Seller KYC documents",p:"Identity and business documents are stored privately and are limited to authorized verification workflows. They are never displayed publicly."},{h:"Sharing and retention",p:"Information is shared only with service providers or authorities where necessary to operate the service, complete lawful requests or protect users. Records are retained only as needed for operations, disputes and legal obligations."},{h:"Your choices",p:"You may request correction or deletion of eligible account information by contacting support. Some transaction or compliance records may need to be retained."}]},
 "terms-and-conditions":{title:"Terms & Conditions",intro:"Rules for using VPANSAK Shopping, Support Hub, Seller Center and related services.",sections:[{h:"Platform use",p:"Use accurate information, keep account access secure and do not misuse the platform. Automated abuse, fraud, impersonation and unlawful listings are prohibited."},{h:"Orders and availability",p:"Product availability, price and delivery estimates may change before an order is confirmed. An order can be cancelled when stock, verification or delivery requirements cannot be completed."},{h:"Payments",p:"Never share an OTP, UPI PIN or card PIN. Payments are processed only after an approved payment partner is connected. Any manual status shown on this version requires verification."},{h:"Content and reviews",p:"Reviews must be truthful, relevant and respectful. VPANSAK may moderate content that is misleading, unsafe, unlawful or unrelated."},{h:"Changes and support",p:"Terms may be updated when services change. Important changes will be reflected on this page. Contact Support Hub for questions or disputes."}]},
 "merchant-guidelines":{title:"Merchant Guidelines",intro:"Standards every VPANSAK seller must follow before and after approval.",sections:[{h:"Accurate registration",p:"Submit genuine business and identity details. The seller email used during registration must match the Seller Dashboard account."},{h:"Product listings",p:"Use accurate names, images, prices, stock, specifications and lawful category information. Counterfeit, misleading, recalled or prohibited products are not allowed."},{h:"Fulfilment",p:"Pack products safely, update inventory promptly and meet confirmed dispatch timelines. Customer information must be used only for fulfilment and support."},{h:"Returns and service",p:"Respond to valid return, replacement and support requests. Sellers must cooperate with investigation of damaged, incorrect or missing products."},{h:"Commission and payouts",p:"Commission, tax and payout terms will be shown before live seller transactions begin. Current dashboard earnings are informational until payment integration is connected."}]},
 "refund-policy":{title:"Refund & Return Policy",intro:"A clear workflow for eligible cancellations, returns, replacements and refunds.",sections:[{h:"Eligibility",p:"Eligibility depends on product condition, category, return window and reason. Some hygiene, personalized, digital or final-sale products may have limited return options."},{h:"Start a request",p:"Create a Return or Refund ticket with the Order ID, item name, reason and supporting details. Do not send sensitive payment credentials."},{h:"Review and pickup",p:"Support may request photographs or arrange inspection or pickup. Keep original packaging and included accessories when possible."},{h:"Refund processing",p:"Approved refunds are sent to the eligible original payment method or another permitted method. Bank processing time may vary."},{h:"Incorrect or damaged items",p:"Report a damaged, missing or incorrect product promptly through the Support Hub so evidence and fulfilment details can be reviewed."}]},
 "shipping-policy":{title:"Shipping Policy",intro:"How VPANSAK handles order confirmation, dispatch, tracking and delivery updates.",sections:[{h:"Order confirmation",p:"A confirmed order receives a VPO Order ID. Track it from the Order Tracking page using that exact ID."},{h:"Dispatch and delivery",p:"Delivery estimates depend on seller readiness, location, courier capacity and service conditions. Status moves through Confirmed, Packed, Shipped, Out for Delivery and Delivered."},{h:"Address accuracy",p:"Customers must provide a complete deliverable address, mobile number and PIN code. Changes may not be possible after dispatch."},{h:"Delivery issues",p:"If tracking is delayed, create a Delivery ticket. Public tracking masks personal information for privacy."},{h:"Failed delivery",p:"An order may be returned after unsuccessful delivery attempts or an undeliverable address. Refund eligibility follows the Refund Policy."}]}
};
export default function PolicyPage(){const {slug}=useParams<{slug:string}>();const policy=policies[slug];if(!policy)return <main className="legal-page"><div className="legal-missing"><FileText/><h1>Policy not found</h1><Link href="/">Return home</Link></div></main>;return <main className="legal-page"><header className="sub-header"><Link className="shop-brand" href="/"><img className="brand-logo" src="/vpansak-logo-dark.jpeg" alt="VPANSAK"/><span><strong>VPANSAK</strong><small>TRUST CENTER</small></span></Link><nav><Link href="/"><ArrowLeft/>Store</Link><Link href="/support">Support</Link></nav></header><section className="legal-hero"><ShieldCheck/><small>VPANSAK TRUST CENTER</small><h1>{policy.title}</h1><p>{policy.intro}</p><span>Last updated: 17 July 2026</span></section><section className="legal-layout"><aside><strong>POLICY DIRECTORY</strong>{Object.entries(policies).map(([key,value])=><Link className={slug===key?"active":""} href={`/policies/${key}`} key={key}>{value.title}</Link>)}</aside><article><div className="legal-notice"><CheckCircle2/><p>This page explains the operating policy in clear language. For an account-specific question, create a support ticket.</p></div>{policy.sections.map((s,i)=><section key={s.h}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{s.h}</h2><p>{s.p}</p></div></section>)}<footer><Mail/><div><strong>Questions about this policy?</strong><p>Contact <a href="mailto:support.vpansak@gmail.com">support.vpansak@gmail.com</a> or use the Support Hub.</p></div></footer></article></section></main>}
