"use client";

import { ArrowLeft, BriefcaseBusiness, ChevronRight, CircleHelp, Mail, Newspaper, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
const pages:Record<string,{eyebrow:string;title:string;intro:string;items:Array<{title:string;text:string}>}>={
 about:{eyebrow:"ABOUT VPANSAK",title:"One digital ecosystem. Many possibilities.",intro:"VPANSAK, powered by A&A Group, brings commerce, seller tools, customer support and responsible community initiatives into one connected platform.",items:[{title:"Our vision",text:"Make digital commerce simpler, safer and more useful for customers, sellers and support teams."},{title:"Shopping",text:"A responsive marketplace with product discovery, account tools, checkout and detailed order tracking."},{title:"Seller growth",text:"Registration, private KYC review, product management and operational support in one Seller Center."},{title:"Service first",text:"Trackable support tickets, officer assignment and clear conversation history for every issue."}]},
 faq:{eyebrow:"FREQUENTLY ASKED QUESTIONS",title:"Quick answers for common questions.",intro:"For an issue linked to your account or order, create a Support Ticket so the conversation remains trackable.",items:[{title:"How do I track an order?",text:"Open Order Tracking and enter the VPO Order ID shown after checkout."},{title:"How do I become a seller?",text:"Complete the Become a Seller form and upload all required KYC documents. Track progress in Seller Center using the same email."},{title:"How do I contact support?",text:"Use the Support Hub to create a ticket. You receive a VPT Ticket ID and can view every reply."},{title:"Are payments live?",text:"COD can be recorded. Online Razorpay and UPI processing require production payment credentials before real collection is enabled."},{title:"How do certificates work?",text:"Foundation entries receive a VPC Certificate ID. The status remains Pending Verification until an admin confirms the contribution."}]},
 careers:{eyebrow:"CAREERS AT VPANSAK",title:"Help build responsible digital commerce.",intro:"Future opportunities may include customer support, merchant operations, technology, finance and creative roles.",items:[{title:"Support operations",text:"Help customers resolve order, payment, delivery and account questions with clear professional communication."},{title:"Merchant success",text:"Guide seller onboarding, listing quality and fulfilment readiness."},{title:"Technology",text:"Build secure storefront, data, automation and mobile experiences."},{title:"How to apply",text:"Send a short introduction and your relevant experience to support.vpansak@gmail.com with the subject Careers at VPANSAK."}]},
 blog:{eyebrow:"VPANSAK JOURNAL",title:"Updates, guides and marketplace stories.",intro:"The publishing area is ready for product guides, seller education, platform announcements and community updates.",items:[{title:"A safer support experience",text:"Why trackable Ticket IDs and reply history make customer service easier to follow."},{title:"Seller listing checklist",text:"A practical guide to accurate images, descriptions, pricing, stock and category information."},{title:"Understanding order tracking",text:"What Confirmed, Packed, Shipped, Out for Delivery and Delivered mean."},{title:"Foundation transparency",text:"How certificate verification clearly separates recorded and verified contributions."}]},
 contact:{eyebrow:"CONTACT VPANSAK",title:"Reach the right team.",intro:"For the fastest resolution, use the Support Hub and select the category that matches your request.",items:[{title:"Customer support",text:"support.vpansak@gmail.com — orders, payments, returns, delivery and account issues."},{title:"Seller support",text:"Use the Seller category in Support Hub for onboarding, KYC, products and merchant questions."},{title:"Website",text:"https://vpansak.vercel.app"},{title:"Social",text:"Official Instagram: @VPANSAK • Founder Instagram: @aloksingh_._"}]}
};
const icons={about:Sparkles,faq:CircleHelp,careers:BriefcaseBusiness,blog:Newspaper,contact:Mail};
export default function InfoPage(){const {slug}=useParams<{slug:string}>();const page=pages[slug];const Icon=icons[slug as keyof typeof icons]||ShieldCheck;if(!page)return <main className="legal-page"><div className="legal-missing"><CircleHelp/><h1>Page not found</h1><Link href="/">Return home</Link></div></main>;return <main className="info-page"><header className="sub-header"><Link className="shop-brand" href="/"><img className="brand-logo" src="/vpansak-logo-dark.jpeg" alt="VPANSAK"/><span><strong>VPANSAK</strong><small>HEADQUARTERS</small></span></Link><nav><Link href="/"><ArrowLeft/>Home</Link><Link href="/support">Support Hub</Link></nav></header><section className="info-hero"><Icon/><small>{page.eyebrow}</small><h1>{page.title}</h1><p>{page.intro}</p></section><section className="info-grid">{page.items.map((item,i)=><article key={item.title}><span>{String(i+1).padStart(2,"0")}</span><h2>{item.title}</h2><p>{item.text}</p></article>)}</section><section className="info-cta"><div><small>NEED PERSONAL HELP?</small><h2>Open the VPANSAK Support Hub.</h2><p>Create and track a ticket with complete reply history.</p></div><Link href="/support">Get support <ChevronRight/></Link></section></main>}
