"use client";

import { ArrowLeft, BriefcaseBusiness, ChevronRight, CircleHelp, Mail, Newspaper, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
const pages:Record<string,{eyebrow:string;title:string;intro:string;items:Array<{title:string;text:string}>}>={
 about:{eyebrow:"ABOUT VPANSAK",title:"Exclusive Direct-to-Consumer Brand.",intro:"VPANSAK, powered by A&A Group, brings high-quality products, direct quality control, customer support and community initiatives into one connected platform.",items:[{title:"Our vision",text:"Deliver 100% genuine VPANSAK in-house manufactured products directly to customers without middleman fees."},{title:"Direct Store",text:"An exclusive D2C brand store with curated products, secure checkout, and real-time order tracking."},{title:"In-House Quality",text:"Multi-stage quality checks and direct fulfillment from VPANSAK hubs."},{title:"Service first",text:"Trackable support tickets, officer assignment and fast 5-minute refund initiation."}]},
 faq:{eyebrow:"FREQUENTLY ASKED QUESTIONS",title:"Quick answers for common questions.",intro:"For an issue linked to your account or order, create a Support Ticket so the conversation remains trackable.",items:[{title:"How do I track an order?",text:"Open Order Tracking and enter the VPO Order ID shown after checkout."},{title:"Are third-party sellers allowed?",text:"No. VPANSAK is an exclusive D2C brand store. We sell only VPANSAK original products."},{title:"How do I contact support?",text:"Use the Support Hub to create a ticket. You receive a VPT Ticket ID and can view every reply."},{title:"Are payments live?",text:"COD and UPI payment processing are supported for instant checkout."},{title:"How do certificates work?",text:"Foundation entries receive a VPC Certificate ID after payment verification."}]},
 careers:{eyebrow:"CAREERS AT VPANSAK",title:"Help build responsible digital commerce.",intro:"Future opportunities may include customer support, product design, quality control, technology, and creative roles.",items:[{title:"Support operations",text:"Help customers resolve order, payment, delivery and account questions with clear professional communication."},{title:"Quality & Fulfillment",text:"Ensure product quality standards, packaging, and dispatch readiness."},{title:"Technology",text:"Build secure storefront, data, automation and mobile experiences."},{title:"How to apply",text:"Send a short introduction and your relevant experience to support.vpansak@gmail.com with the subject Careers at VPANSAK."}]},
 blog:{eyebrow:"VPANSAK JOURNAL",title:"Updates, guides and brand stories.",intro:"The publishing area is ready for product guides, brand stories, platform announcements and community updates.",items:[{title:"A safer support experience",text:"Why trackable Ticket IDs and reply history make customer service easier to follow."},{title:"Direct Brand Quality",text:"Why VPANSAK controls manufacturing and fulfillment directly."},{title:"Understanding order tracking",text:"What Confirmed, Packed, Shipped, Out for Delivery and Delivered mean."},{title:"Foundation transparency",text:"How certificate verification clearly separates recorded and verified contributions."}]},
 contact:{eyebrow:"CONTACT VPANSAK",title:"Reach the right team.",intro:"For the fastest resolution, use the Support Hub and select the category that matches your request.",items:[{title:"Customer support",text:"support.vpansak@gmail.com — orders, payments, returns, delivery and account issues."},{title:"Brand inquiries",text:"Use the Support Hub for product, media, or partnership questions."},{title:"Website",text:"https://vpansak.vercel.app"},{title:"Social",text:"Official Instagram: @VPANSAK • Founder Instagram: @aloksingh_._"}]}
};
const icons={about:Sparkles,faq:CircleHelp,careers:BriefcaseBusiness,blog:Newspaper,contact:Mail};
export default function InfoPage(){const {slug}=useParams<{slug:string}>();const page=pages[slug];const Icon=icons[slug as keyof typeof icons]||ShieldCheck;if(!page)return <main className="legal-page"><div className="legal-missing"><CircleHelp/><h1>Page not found</h1><Link href="/">Return home</Link></div></main>;return <main className="info-page"><header className="sub-header"><Link className="shop-brand" href="/"><img className="brand-logo" src="/vpansak-logo-dark.jpeg" alt="VPANSAK"/><span><strong>VPANSAK</strong><small>HEADQUARTERS</small></span></Link><nav><Link href="/"><ArrowLeft/>Home</Link><a href="https://vpansaksupporthub.lovable.app/" target="_blank" rel="noreferrer">Support Hub</a></nav></header><section className="info-hero"><Icon/><small>{page.eyebrow}</small><h1>{page.title}</h1><p>{page.intro}</p></section><section className="info-grid">{page.items.map((item,i)=><article key={item.title}><span>{String(i+1).padStart(2,"0")}</span><h2>{item.title}</h2><p>{item.text}</p></article>)}</section><section className="info-cta"><div><small>NEED PERSONAL HELP?</small><h2>Open the VPANSAK Support Hub.</h2><p>Create and track a ticket with complete reply history.</p></div><a href="https://vpansaksupporthub.lovable.app/" target="_blank" rel="noreferrer">Get support <ChevronRight/></a></section></main>}

